# -*- coding: utf-8 -*-
"""Atividades-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqoQCid-yaewhqcisF2r39mgQjewvfhK
"""

valor_casa = float(input('\nInforme o valor do imovel: '))
salario = float(input('Informe o salário: '))
anos = int(input('Informe em quantos anos será pago: '))

quant_prest = anos * 12
prest_mensal = valor_casa/quant_prest

if salario * 0.3 > prest_mensal:
    print('\n\nSeu empréstimo bancário foi aprovado!!')
    print('Você pagará {} prestações de R${:.2f} por {} anos'.format(quant_prest, prest_mensal, anos))

else:
    print('Infelizmente você não foi aprovado para o empréstimo, sentimos muito.')

print('\nA confederação nacional de natação precisa de um programa que leia o ano de nascimento de um atleta e mostre sua\ncategoria, de acordo com a sua idade:'
      '\n-Até 9 anos: MIRIM'
      '\n-Até 14 anos: INFANTIL'
      '\n-Até 19 anos: JUNIOR'
      '\n-Até 20 anos: SÊNIOR'
      '\n-Acima: MASTER\n')

idade = int(input('Informe sua idade: '))

if idade >= 9:
    print("Sua Liga é MIRIM")
elif idade > 9 and idade <= 14:
    print("Sua Liga é INFANTIL")
elif idade > 14 and idade <= 19:
    print("Sua liga é JUNIOR")
elif idade > 19:
    print("Sua liga é SÊNIOR")
elif idade <= 0 or idade >= 120:
    print('Não é possível competir com essa idade.')

# - Analisador de Textos

from time import sleep

nome = str(input("Digite seu nome completo: ")).strip()
print("-" * 25)
print("Analisando seu nome...")
print("-" * 25)
sleep(5)
print()
print("Seu nome é {}" .format(nome))
print("Seu nome em maiúsculo é {}" .format(nome.upper()))
print("Seu nome em minúsculo é {}" .format(nome.lower()))
print("Seu nome tem {} letras".format(len(nome)- nome.count(" ")))
#print("Seu primeiro nome tem {} letras".format(nome.find(" ")))
separa = nome.split()
print("Seu primeiro nome é {} e ele tem {} letras" .format(separa[0], len(separa[0])))

# Escreva uma função chamada fatorial que receba um número inteiro como parâmetro e retorne o fatorial desse número.

def fatorial(n):
  if n==0 or n==1:
    return 1
  else:
    return n * fatorial(n-1)

numero = int(input("Escreva o número que queira descubrir o fatorial: "))

print(f"O Fatorial de {numero} é igual á {fatorial(numero)}")

#Escreva um programa que verifique se uma palavra digitada pelo usuário é um palíndromo (uma palavra que é igual de trás para frente).

palavra = input("Digite uma palavra: ").lower()
if palavra == palavra[::-1]:
  print(f"A palavra {palavra} é um palindromo")
else:
  print(f"A palavra {palavra} não é um palindromo")